#!/usr/bin/env python3
"""
Theme Manager - Sur5ve Protected Theming System

Sur5ve LLC - Proprietary Visual Identity Module
Copyright (c) 2024-2026 Sur5ve LLC
Licensed under MIT License
https://sur5ve.com

This module is a core component of the Sur5ve brand identity.
Theme color palettes are loaded from JSON files in theme_data/ directory.
"""

import json
from pathlib import Path
from typing import Dict, Any, Optional, List
from PySide6.QtWidgets import QApplication, QWidget
from PySide6.QtCore import QObject, Signal


# Theme data directory (relative to this file)
THEME_DATA_DIR = Path(__file__).parent / "theme_data"


def _load_theme_from_json(theme_key: str) -> Optional[Dict[str, str]]:
    """Load theme colors from JSON file in theme_data/ directory."""
    theme_file = THEME_DATA_DIR / f"{theme_key}.json"
    if not theme_file.exists():
        print(f"⚠️ Theme file not found: {theme_file}")
        return None
    
    try:
        with open(theme_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data.get("colors", {})
    except Exception as e:
        print(f"❌ Error loading theme {theme_key}: {e}")
        return None


def _discover_themes() -> Dict[str, str]:
    """Discover available themes from JSON files and build display mapping."""
    themes = {}
    if not THEME_DATA_DIR.exists():
        return themes
    
    for theme_file in THEME_DATA_DIR.glob("*.json"):
        theme_key = theme_file.stem
        try:
            with open(theme_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            themes[theme_key] = data.get("name", theme_key.replace("_", " ").title())
        except Exception:
            themes[theme_key] = theme_key.replace("_", " ").title()
    
    return themes


# Centralized theme display mapping for user-facing UI labels
# Dynamically built from theme_data/ JSON files
THEME_KEY_TO_DISPLAY = _discover_themes()

# Fallback if no themes found - Sur5ve is the only supported theme
if not THEME_KEY_TO_DISPLAY:
    THEME_KEY_TO_DISPLAY = {
        "sur5ve": "Sur5ve",
    }

THEME_DISPLAY_TO_KEY = {v: k for k, v in THEME_KEY_TO_DISPLAY.items()}


class ThemeManager(QObject):
    """Manages application themes with QSS styling.
    
    Theme color palettes are loaded from JSON files in themes/theme_data/.
    """
    
    # Signals
    theme_changed = Signal(str)  # theme_name
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.current_theme: Optional[str] = None
        self._setup_themes()
        
    def _setup_themes(self):
        """Initialize all available themes from JSON files."""
        self.themes = {}
        
        for theme_key in THEME_KEY_TO_DISPLAY.keys():
            colors = _load_theme_from_json(theme_key)
            if colors:
                self.themes[theme_key] = colors
            else:
                # Fallback to hardcoded if JSON not found
                fallback = self._get_fallback_theme(theme_key)
                if fallback:
                    self.themes[theme_key] = fallback
        
        print(f"[Theme] Loaded {len(self.themes)} themes: {', '.join(self.themes.keys())}")
    
    def _get_fallback_theme(self, theme_key: str) -> Optional[Dict[str, str]]:
        """Get fallback theme colors if JSON file not found.
        
        Sur5ve Protected - Brand Identity Fallback
        """
        # Sur5ve is the only supported theme
        if theme_key == "sur5ve":
            return {
                "primary": "#bd93f9", "primary_hover": "#ff79c6",
                "secondary": "#6272a4", "accent": "#50fa7b",
                "danger": "#ff5555", "danger_hover": "#ff6e6e",
                "bg_primary": "#282a36", "bg_secondary": "#21222c",
                "bg_tertiary": "#44475a", "bg_quaternary": "#6272a4",
                "text_primary": "#f8f8f2", "text_secondary": "#f8f8f2",
                "text_muted": "#6272a4", "text_error": "#ff5555", "text_success": "#50fa7b",
                "border": "#44475a", "border_focus": "#bd93f9", "border_hover": "#6272a4",
                "selection": "#bd93f9", "selection_bg": "rgba(189, 147, 249, 0.2)",
                "shadow": "rgba(0, 0, 0, 0.4)",
            }
        return None
        
    def _generate_comprehensive_qss(self, colors: Dict[str, str], font_size: int = None) -> str:
        """Generate comprehensive QSS stylesheet from color palette with dynamic font size.
        
        This method combines all component stylesheets into a single QSS string.
        Each component is generated by a separate method for better maintainability.
        """
        # Resolve optional tokens with sensible fallbacks
        danger_color = colors.get('danger', colors.get('text_error', '#ff6b6b'))
        danger_hover = colors.get('danger_hover', '#ff7f7f')
        focus_outline = colors.get('border_focus', '#00d4aa')
        
        # Get current font size from application if not provided
        if font_size is None:
            app = QApplication.instance()
            font_size = app.font().pointSize() if app else 9
        
        # Calculate scaled sizes based on base font
        font_size_large = font_size + 4
        font_size_xlarge = font_size + 15
        
        # Shared chat radii so history + composer stay visually aligned
        chat_surface_radius = 8
        chat_inner_radius = max(chat_surface_radius - 2, 4)
        
        # Build QSS from component methods
        return "\n".join([
            self._qss_base_widgets(colors, font_size, focus_outline),
            self._qss_buttons(colors, font_size, danger_color, danger_hover, focus_outline),
            self._qss_inputs(colors, font_size, chat_surface_radius, chat_inner_radius),
            self._qss_labels(colors, font_size, font_size_large, font_size_xlarge),
            self._qss_scrollbars(colors, chat_surface_radius, chat_inner_radius),
            self._qss_menus(colors, font_size),
            self._qss_controls(colors, font_size),
            self._qss_chat_bubbles(colors, font_size, chat_surface_radius, chat_inner_radius),
            self._qss_misc(colors, font_size, chat_surface_radius, danger_color, danger_hover),
        ])
    
    def _qss_base_widgets(self, colors: Dict[str, str], font_size: int, focus_outline: str) -> str:
        """Generate QSS for base widget styling (QMainWindow, QWidget, focus)."""
        return f"""
        /* Main Application Styling */
        QMainWindow {{
            background-color: {colors['bg_primary']};
            color: {colors['text_primary']};
            font-size: {font_size}pt;
        }}
        
        /* General Widget Styling */
        QWidget {{
            background-color: {colors['bg_primary']};
            color: {colors['text_primary']};
            font-family: "Segoe UI", "SF Pro Display", sans-serif;
            font-size: {font_size}pt;
        }}

        /* Global focus outline for accessibility - exclude elements with custom focus handling */
        QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {{
            outline: none;
            border-color: {focus_outline};
        }}
        
        /* Disable global focus outline to prevent ugly focus boxes */
        QCheckBox:focus, QRadioButton:focus, QPushButton:focus, QComboBox:focus {{
            outline: none;
        }}
        """
    
    def _qss_buttons(self, colors: Dict[str, str], font_size: int, danger_color: str, danger_hover: str, focus_outline: str) -> str:
        """Generate QSS for all button variants."""
        return f"""
        /* Buttons */
        QPushButton {{
            background-color: {colors['bg_secondary']};
            border: 1px solid {colors['border']};
            border-radius: 8px;
            padding: 8px 16px;
            color: {colors['text_primary']};
            font-weight: 500;
            min-height: 34px;
        }}
        
        QPushButton:hover {{
            background-color: {colors['bg_tertiary']};
            border-color: {colors['border_hover']};
        }}
        
        QPushButton:pressed {{
            background-color: {colors['bg_quaternary']};
        }}
        
        QPushButton:disabled {{
            background-color: {colors['bg_tertiary']};
            color: {colors['text_muted']};
            border-color: {colors['border']};
        }}
        
        /* Primary buttons */
        QPushButton[class="primary"], QPushButton#primary {{
            background-color: {colors['primary']};
            border-color: {colors['primary']};
            color: white;
            font-weight: 600;
        }}
        
        QPushButton[class="primary"]:hover, QPushButton#primary:hover {{
            background-color: {colors['primary_hover']};
            border-color: {colors['primary_hover']};
        }}
        
        QPushButton[class="primary"]:disabled, QPushButton#primary:disabled {{
            background-color: {colors['text_muted']};
            border-color: {colors['text_muted']};
        }}

        /* Secondary buttons */
        QPushButton[class="secondary"], QPushButton#secondary {{
            background-color: {colors['bg_tertiary']};
            border: 1px solid {colors['border_hover']};
            color: {colors['text_primary']};
        }}

        /* Danger buttons (coral) */
        QPushButton[class="danger"], QPushButton#danger {{
            background-color: {danger_color};
            border-color: {danger_color};
            color: white;
            font-weight: 600;
        }}
        QPushButton[class="danger"]:hover, QPushButton#danger:hover {{
            background-color: {danger_hover};
            border-color: {danger_hover};
        }}
        QPushButton[class="danger"]:disabled, QPushButton#danger:disabled {{
            background-color: {colors['text_muted']};
            border-color: {colors['text_muted']};
        }}
        
        /* QMessageBox and QDialog button styling - Remove ugly blue focus box */
        QMessageBox QPushButton {{
            min-width: 80px;
            padding: 6px 16px;
        }}
        
        QMessageBox QPushButton:focus,
        QDialogButtonBox QPushButton:focus {{
            outline: none;
            border: 2px solid {focus_outline};
            border-radius: 8px;
        }}
        
        /* Style Yes/No buttons in message boxes */
        QMessageBox QPushButton[text="Yes"],
        QMessageBox QPushButton[text="&Yes"] {{
            background-color: {colors['primary']};
            color: white;
            font-weight: 600;
        }}
        
        QMessageBox QPushButton[text="Yes"]:hover,
        QMessageBox QPushButton[text="&Yes"]:hover {{
            background-color: {colors['primary_hover']};
        }}
        
        QMessageBox QPushButton[text="No"],
        QMessageBox QPushButton[text="&No"] {{
            background-color: {colors['bg_tertiary']};
            border: 1px solid {colors['border_hover']};
        }}
        
        QMessageBox QPushButton[text="No"]:hover,
        QMessageBox QPushButton[text="&No"]:hover {{
            background-color: {colors['bg_quaternary']};
        }}
        
        /* Remove default focus rectangle for all widgets in dialogs */
        QDialog QPushButton:focus,
        QDialog QComboBox:focus,
        QDialog QLineEdit:focus,
        QDialog QCheckBox:focus {{
            outline: none;
        }}
        
        /* Add subtle focus border instead of blue box */
        QDialog QPushButton:focus {{
            border: 2px solid {focus_outline};
        }}
        """
    
    def _qss_inputs(self, colors: Dict[str, str], font_size: int, chat_surface_radius: int, chat_inner_radius: int) -> str:
        """Generate QSS for text inputs, line edits, and text areas."""
        return f"""
        /* Text Input Fields */
        QTextEdit, QPlainTextEdit {{
            background-color: {colors['bg_secondary']};
            border: 1px solid {colors['border']};
            border-radius: 8px;
            padding: 8px;
            color: {colors['text_primary']};
            selection-background-color: {colors['selection_bg']};
        }}
        
        QTextEdit:focus, QPlainTextEdit:focus {{
            border-color: {colors['border_focus']};
        }}

        /* Message composer - keep input inset from rounded edges */
        MessageComposer QFrame {{
            background-color: {colors['bg_secondary']};
            border: 1px solid {colors['border']};
            border-radius: {chat_surface_radius}px;
            padding: 6px;  /* keeps caret/content off rounded edge */
        }}

        MessageComposer QTextEdit {{
            background-color: transparent;
            border: none;
            border-radius: {chat_inner_radius}px;
            padding: 4px 6px;
        }}
        
        QLineEdit {{
            background-color: {colors['bg_secondary']};
            border: 1px solid {colors['border']};
            border-radius: 6px;
            padding: 6px 10px;
            color: {colors['text_primary']};
            min-height: 34px;
        }}
        
        QLineEdit:focus {{
            border-color: {colors['border_focus']};
        }}
        """
    
    def _qss_labels(self, colors: Dict[str, str], font_size: int, font_size_large: int, font_size_xlarge: int) -> str:
        """Generate QSS for labels and label variants."""
        return f"""
        /* Labels */
        QLabel {{
            color: {colors['text_primary']};
            background-color: transparent;
            font-size: {font_size}pt;
        }}
        
        QLabel[class="welcome_label"] {{
            color: {colors['primary']};
            font-size: {font_size_xlarge}pt;
            font-weight: bold;
            margin-bottom: 16px;
        }}
        
        QLabel[class="instructions_label"] {{
            color: {colors['text_muted']};
            font-size: {font_size_large}pt;
            line-height: 1.5;
        }}
        
        QLabel[class="error_message"] {{
            color: {colors['text_error']};
            background-color: {colors['bg_secondary']};
            padding: 8px;
            border-radius: 6px;
        }}
        
        /* Sur Branding Label */
        QLabel[class="sur_branding"] {{
            color: #ffffff;
            font-weight: bold;
            font-size: 10px;
            padding: 3px 8px;
            background-color: {colors['primary']};
            border: none;
            border-radius: 4px;
            margin-bottom: 2px;
        }}
        """
    
    def _qss_scrollbars(self, colors: Dict[str, str], chat_surface_radius: int, chat_inner_radius: int) -> str:
        """Generate QSS for scroll areas and scrollbars."""
        return f"""
        /* Scroll Areas */
        QScrollArea {{
            background-color: {colors['bg_primary']};
            border: none;
        }}
        
        /* Thread View - Chat History Area (matched to composer corners) */
        QScrollArea#thread_view,
        QScrollArea[class="thread_view"] {{
            background-color: transparent;  /* transparent so we only see viewport background */
            border: 1px solid {colors['border']};
            border-radius: {chat_surface_radius}px;
            padding: 2px;  /* Padding creates space between border and viewport */
        }}
        
        /* Viewport - CRITICAL: Must be styled to respect parent's rounded corners */
        QScrollArea#thread_view QWidget#qt_scrollarea_viewport,
        QScrollArea[class="thread_view"] QWidget#qt_scrollarea_viewport {{
            background-color: {colors['bg_secondary']};
            border-radius: {chat_inner_radius}px;  /* smaller radius to fit inside border */
            margin: 0px;  /* No margin needed now - padding on parent handles spacing */
            padding: 0px;
        }}
        
        /* Content widget - where messages actually live */
        QScrollArea#thread_view > QWidget,
        QScrollArea[class="thread_view"] > QWidget {{
            background-color: transparent;  /* transparent so viewport bg shows through */
            border-radius: 0px;  /* no border-radius here, let viewport handle it */
            margin: 0px;
            padding: 0px;
        }}
        
        /* Scroll Bars */
        QScrollBar:vertical {{
            background-color: {colors['bg_tertiary']};
            width: 12px;
            border-radius: 6px;
            margin: 0;
        }}
        
        QScrollBar::handle:vertical {{
            background-color: {colors['border_hover']};
            border-radius: 6px;
            min-height: 20px;
        }}
        
        QScrollBar::handle:vertical:hover {{
            background-color: {colors['text_muted']};
        }}
        
        QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
            border: none;
            background: none;
        }}
        
        /* Horizontal scroll bar */
        QScrollBar:horizontal {{
            background-color: {colors['bg_tertiary']};
            height: 12px;
            border-radius: 6px;
            margin: 0;
        }}
        
        QScrollBar::handle:horizontal {{
            background-color: {colors['border_hover']};
            border-radius: 6px;
            min-width: 20px;
        }}
        
        QScrollBar::handle:horizontal:hover {{
            background-color: {colors['text_muted']};
        }}
        
        QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
            border: none;
            background: none;
        }}
        
        /* Splitters */
        QSplitter::handle {{
            background-color: {colors['border']};
        }}
        
        QSplitter::handle:horizontal {{
            width: 1px;
        }}
        
        QSplitter::handle:vertical {{
            height: 1px;
        }}
        """
    
    def _qss_menus(self, colors: Dict[str, str], font_size: int) -> str:
        """Generate QSS for menu bar, menus, and status bar."""
        return f"""
        /* Menu Bar */
        QMenuBar {{
            background-color: {colors['bg_primary']};
            color: {colors['text_primary']};
            border-bottom: 1px solid {colors['border']};
            padding: 4px;
        }}
        
        QMenuBar::item {{
            background-color: transparent;
            padding: 6px 12px;
            border-radius: 4px;
        }}
        
        QMenuBar::item:selected {{
            background-color: {colors['bg_secondary']};
        }}
        
        QMenuBar::item:pressed {{
            background-color: {colors['bg_tertiary']};
        }}
        
        /* Menus */
        QMenu {{
            background-color: {colors['bg_secondary']};
            color: {colors['text_primary']};
            border: 1px solid {colors['border']};
            border-radius: 8px;
            padding: 4px;
        }}
        
        QMenu::item {{
            background-color: transparent;
            padding: 8px 24px;
            border-radius: 4px;
        }}
        
        QMenu::item:selected {{
            background-color: {colors['bg_tertiary']};
        }}
        
        QMenu::separator {{
            height: 1px;
            background-color: {colors['border']};
            margin: 4px 0;
        }}
        
        /* Status Bar */
        QStatusBar {{
            background-color: {colors['bg_primary']};
            color: {colors['text_secondary']};
            border-top: 1px solid {colors['border']};
            padding: 4px;
        }}
        """
    
    def _qss_controls(self, colors: Dict[str, str], font_size: int) -> str:
        """Generate QSS for form controls (combo boxes, checkboxes, radio buttons, progress bars)."""
        return f"""
        /* Combo Boxes */
        QComboBox {{
            background-color: {colors['bg_secondary']};
            border: 1px solid {colors['border']};
            border-radius: 6px;
            padding: 6px 10px;
            color: {colors['text_primary']};
            min-height: 34px;
        }}
        
        QComboBox:hover {{
            border-color: {colors['border_hover']};
        }}
        
        QComboBox:focus {{
            border-color: {colors['border_focus']};
        }}
        QComboBox:disabled {{
            background-color: {colors['bg_tertiary']};
            color: {colors['text_muted']};
            border-color: {colors['border']};
        }}
        
        QComboBox::drop-down {{
            border: none;
            width: 20px;
        }}
        
        QComboBox::down-arrow {{
            width: 12px;
            height: 12px;
        }}
        
        QComboBox QAbstractItemView {{
            background-color: {colors['bg_secondary']};
            border: 1px solid {colors['border']};
            border-radius: 8px;
            color: {colors['text_primary']};
            selection-background-color: {colors['selection_bg']};
            outline: none;
        }}
        
        /* Group Boxes - reserve space for title chip using margin-top */
        QGroupBox {{
            background-color: {colors['bg_secondary']};
            border: 1px solid {colors['border']};
            border-radius: 10px;
            margin: 0; /* inter-group spacing comes from parent layout spacing */
            margin-top: 16px; /* room for title chip */
            padding: 0; /* content inset comes from layout margins */
            font-weight: 600;
            box-sizing: border-box;
        }}
        
        QGroupBox::title {{
            subcontrol-origin: margin;
            subcontrol-position: top left;
            left: 12px; /* align title with content inset */
            padding: 2px 6px;
            color: {colors['text_primary']};
            background-color: {colors['bg_secondary']};
            border-radius: 4px;
        }}
        
        /* Labels inside group boxes - ensure text never overflows */
        QGroupBox QLabel {{
            padding: 0;
            margin: 0;
            /* QSS doesn't support word-break directly, handle in Python with wordWrap */
            /* Text wrapping and max-width are controlled via Python API */
        }}

        /* Panel row container for consistent inner spacing */
        QFrame[class="panel_row"] {{
            background-color: {colors['bg_secondary']};
            border: 1px solid {colors['border']};
            border-radius: 10px;
            padding: 10px;
            margin: 6px 0 10px 0;
        }}
        
        /* Check Boxes */
        QCheckBox {{
            color: {colors['text_primary']};
            spacing: 8px;
            outline: none;
        }}
        
        /* Remove ugly blue focus box from checkboxes */
        QCheckBox:focus {{
            outline: none;
        }}
        
        QCheckBox::indicator {{
            width: 16px;
            height: 16px;
            border: 1px solid {colors['border']};
            border-radius: 3px;
            background-color: {colors['bg_secondary']};
        }}
        
        QCheckBox::indicator:hover {{
            border-color: {colors['border_hover']};
        }}
        
        /* Focus indicator on the checkbox indicator itself */
        QCheckBox::indicator:focus {{
            border-color: {colors['border_focus']};
            border-width: 2px;
        }}
        
        QCheckBox::indicator:checked {{
            background-color: {colors['primary']};
            border-color: {colors['primary']};
        }}
        
        QCheckBox::indicator:checked:focus {{
            border-color: {colors['primary']};
            border-width: 2px;
        }}
        
        /* Radio Buttons */
        QRadioButton {{
            color: {colors['text_primary']};
            spacing: 8px;
        }}
        
        QRadioButton::indicator {{
            width: 16px;
            height: 16px;
            border: 1px solid {colors['border']};
            border-radius: 8px;
            background-color: {colors['bg_secondary']};
        }}
        
        QRadioButton::indicator:hover {{
            border-color: {colors['border_hover']};
        }}
        
        QRadioButton::indicator:checked {{
            background-color: {colors['primary']};
            border-color: {colors['primary']};
        }}
        
        /* Progress Bars */
        QProgressBar {{
            background-color: {colors['bg_secondary']};
            border: 1px solid {colors['border']};
            border-radius: 6px;
            text-align: center;
            color: {colors['text_primary']};
        }}
        
        QProgressBar::chunk {{
            background-color: {colors['primary']};
            border-radius: 5px;
        }}
        """
    
    def _qss_chat_bubbles(self, colors: Dict[str, str], font_size: int, chat_surface_radius: int, chat_inner_radius: int) -> str:
        """Generate QSS for chat message bubbles, thinking bubbles, and related elements."""
        return f"""
        /* Message Bubbles */
        QFrame[class="user_bubble"] {{
            background-color: {colors['primary']};
            border-radius: {chat_surface_radius}px;
            padding: 12px 16px;
            margin: 4px 0px;
            border: none;
        }}
        
        QFrame[class="assistant_bubble"] {{
            background-color: {colors['bg_tertiary']};
            border-radius: {chat_surface_radius}px;
            padding: 12px 16px;
            margin: 4px 0px;
            border: none;
        }}
        
        /* QTextBrowser in message bubbles */
        QTextBrowser[class="message_content"] {{
            background-color: transparent;
            border: none;
            padding: 4px;
            color: {colors['text_primary']};
        }}
        
        QTextBrowser[class="message_content"]:focus {{
            border: none;
            outline: none;
        }}
        
        /* Thinking bubble specific styling */
        QFrame[class="thinking_bubble"] {{
            background-color: rgba(88, 95, 161, 0.15);
            border-radius: {chat_inner_radius}px;
            padding: 12px 16px;
            margin: 4px 0px;
            border: 1px solid rgba(88, 95, 161, 0.3);
        }}
        
        /* Collapsible thinking header button */
        QPushButton[class="collapsible_header"] {{
            background-color: rgba(88, 95, 161, 0.2);
            border: 1px solid rgba(88, 95, 161, 0.4);
            border-radius: 6px;
            padding: 8px 12px;
            text-align: left;
            color: {colors['text_primary']};
            font-size: {font_size}pt;
            font-weight: 500;
            outline: none;
        }}
        
        QPushButton[class="collapsible_header"]:hover {{
            background-color: rgba(88, 95, 161, 0.3);
            border-color: rgba(88, 95, 161, 0.5);
        }}
        
        QPushButton[class="collapsible_header"]:pressed {{
            background-color: rgba(88, 95, 161, 0.35);
        }}
        
        QPushButton[class="collapsible_header"]:checked {{
            background-color: rgba(88, 95, 161, 0.25);
        }}
        
        QPushButton[class="collapsible_header"]:focus {{
            outline: none;
            border: 1px solid rgba(88, 95, 161, 0.4);
        }}
        
        /* Collapsible thinking content area */
        QFrame[class="thinking_content"] {{
            background-color: rgba(88, 95, 161, 0.1);
            border: 1px solid rgba(88, 95, 161, 0.2);
            border-radius: {chat_inner_radius}px;
            margin-top: 4px;
            padding: 8px;
        }}
        
        /* Copy button in messages - improved visibility */
        QPushButton[class="message_copy_btn"] {{
            background-color: rgba(255, 255, 255, 0.05);
            border: 1px solid rgba(200, 200, 200, 0.4);
            border-radius: 3px;
            padding: 2px 6px;
            color: rgba(220, 220, 220, 0.95);
            font-size: {font_size - 2}pt;
            font-weight: 500;
        }}
        
        QPushButton[class="message_copy_btn"]:hover {{
            background-color: rgba(255, 255, 255, 0.12);
            border-color: rgba(220, 220, 220, 0.6);
            color: #FFFFFF;
        }}
        
        QPushButton[class="message_copy_btn"]:pressed {{
            background-color: rgba(255, 255, 255, 0.18);
            border-color: rgba(220, 220, 220, 0.7);
        }}
        
        /* Remove blue focus outline on copy button */
        QPushButton[class="message_copy_btn"]:focus {{
            outline: none;
            border: 1px solid rgba(220, 220, 220, 0.6);
        }}
        """
    
    def _qss_misc(self, colors: Dict[str, str], font_size: int, chat_surface_radius: int, danger_color: str, danger_hover: str) -> str:
        """Generate QSS for miscellaneous elements (error indicators, processing header, control hub, tooltips)."""
        return f"""
        QFrame[class="error_indicator"] {{
            border: 2px solid {colors['text_error']};
            border-radius: 12px;
            background-color: rgba(231, 76, 60, 0.1);
        }}

        /* Processing Header */
        #ProcessingHeader {{
            border: 1px solid {colors['border']};
            border-radius: {chat_surface_radius}px;
            background-color: {colors['bg_secondary']};
        }}

        #ProcessingHeaderLabel {{
            color: {colors['text_primary']};
            font-weight: 600;
        }}

        #ProcessingHeaderDots {{
            color: {colors['text_muted']};
            min-width: 1.6em;
        }}

        #ProcessingSkip {{
            color: {colors['text_muted']};
            background: transparent;
            border: none;
            padding: 0 2px;
        }}

        #ProcessingSkip:hover {{
            color: {colors['text_primary']};
            text-decoration: underline;
        }}

        #ProcessingSkip:disabled {{
            color: {colors['text_muted']};
            opacity: 0.5;
        }}

        /* Control Hub Tab */
        ControlHubTab {{
            background-color: {danger_color};
            border: 1px solid {danger_color};
            border-radius: 6px;
            color: white;
            font-weight: 600;
        }}
        
        ControlHubTab:hover {{
            background-color: {danger_hover};
            border-color: {danger_hover};
        }}

        
        /* Tooltips */
        QToolTip {{
            background-color: {colors['bg_quaternary']};
            color: {colors['text_primary']};
            border: 1px solid {colors['border']};
            border-radius: 6px;
            padding: 6px;
        }}
        """
        
    def get_available_themes(self) -> List[str]:
        """Get list of available theme names"""
        return list(self.themes.keys())
        
    def apply_theme(self, theme_name: str, widget: Optional[QWidget] = None, font_size: int = None):
        """Apply a theme to the application or specific widget with dynamic font size"""
        if theme_name not in self.themes:
            print(f"⚠️ Theme '{theme_name}' not found. Available: {list(self.themes.keys())}")
            return False
            
        try:
            # Get current font size if not provided
            if font_size is None:
                app = QApplication.instance()
                font_size = app.font().pointSize() if app else 9
            
            colors = self.themes[theme_name]
            qss = self._generate_comprehensive_qss(colors, font_size)
            
            # Get the main window to apply theme to
            # avoid app.setStyleSheet() - affects all widgets
            # including splash screens. Instead, apply only to non-splash windows.
            app = QApplication.instance()
            if app:
                # Find all top-level widgets that are NOT splash screens
                for w in app.topLevelWidgets():
                    # Skip splash screens by checking objectName AND class name
                    if w.objectName() == "SplashScreen":
                        continue
                    if "SplashScreen" in w.__class__.__name__:
                        continue
                    # Apply stylesheet to this window
                    w.setStyleSheet(qss)
            
            # If specific widget provided, apply to it too
            if widget:
                widget.setStyleSheet(qss)
                    
            self.current_theme = theme_name
            self.theme_changed.emit(theme_name)
            
            print(f"🎨 Theme applied: {theme_name} (font: {font_size}pt)")
            return True
            
        except Exception as e:
            print(f"❌ Error applying theme '{theme_name}': {e}")
            import traceback
            traceback.print_exc()
            return False
            
    def get_current_theme(self) -> Optional[str]:
        """Get the currently applied theme name"""
        return self.current_theme
        
    def get_theme_colors(self, theme_name: str) -> Optional[Dict[str, str]]:
        """Get color palette for a specific theme"""
        return self.themes.get(theme_name)
        
    def reload_current_theme(self):
        """Reload the currently applied theme"""
        if self.current_theme:
            self.apply_theme(self.current_theme)
